# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tu-dien' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'SwiftGoogleTranslate'




  # Pods for tu-dien

end
